// Code generated by tutone: DO NOT EDIT
package synthetics

import "context"

// Create a Synthetics Private Location
func (a *Synthetics) SyntheticsCreatePrivateLocation(
	accountID int,
	description string,
	name string,
	verifiedScriptExecution bool,
) (*SyntheticsPrivateLocationMutationResult, error) {
	return a.SyntheticsCreatePrivateLocationWithContext(context.Background(),
		accountID,
		description,
		name,
		verifiedScriptExecution,
	)
}

// Create a Synthetics Private Location
func (a *Synthetics) SyntheticsCreatePrivateLocationWithContext(
	ctx context.Context,
	accountID int,
	description string,
	name string,
	verifiedScriptExecution bool,
) (*SyntheticsPrivateLocationMutationResult, error) {

	resp := SyntheticsCreatePrivateLocationQueryResponse{}
	vars := map[string]interface{}{
		"accountId":               accountID,
		"description":             description,
		"name":                    name,
		"verifiedScriptExecution": verifiedScriptExecution,
	}

	if err := a.client.NerdGraphQueryWithContext(ctx, SyntheticsCreatePrivateLocationMutation, vars, &resp); err != nil {
		return nil, err
	}

	return &resp.SyntheticsPrivateLocationMutationResult, nil
}

type SyntheticsCreatePrivateLocationQueryResponse struct {
	SyntheticsPrivateLocationMutationResult SyntheticsPrivateLocationMutationResult `json:"SyntheticsCreatePrivateLocation"`
}

const SyntheticsCreatePrivateLocationMutation = `mutation(
	$accountId: Int!,
	$description: String,
	$name: String!,
	$verifiedScriptExecution: Boolean!,
) { syntheticsCreatePrivateLocation(
	accountId: $accountId,
	description: $description,
	name: $name,
	verifiedScriptExecution: $verifiedScriptExecution,
) {
	accountId
	description
	domainId
	errors {
		description
		type
	}
	guid
	key
	locationId
	name
	verifiedScriptExecution
} }`

// Queues a request to create a secure credential
func (a *Synthetics) SyntheticsCreateSecureCredential(
	accountID int,
	description string,
	key string,
	value SecureValue,
) (*SyntheticsSecureCredentialMutationResult, error) {
	return a.SyntheticsCreateSecureCredentialWithContext(context.Background(),
		accountID,
		description,
		key,
		value,
	)
}

// Queues a request to create a secure credential
func (a *Synthetics) SyntheticsCreateSecureCredentialWithContext(
	ctx context.Context,
	accountID int,
	description string,
	key string,
	value SecureValue,
) (*SyntheticsSecureCredentialMutationResult, error) {

	resp := SyntheticsCreateSecureCredentialQueryResponse{}
	vars := map[string]interface{}{
		"accountId":   accountID,
		"description": description,
		"key":         key,
		"value":       value,
	}

	if err := a.client.NerdGraphQueryWithContext(ctx, SyntheticsCreateSecureCredentialMutation, vars, &resp); err != nil {
		return nil, err
	}

	return &resp.SyntheticsSecureCredentialMutationResult, nil
}

type SyntheticsCreateSecureCredentialQueryResponse struct {
	SyntheticsSecureCredentialMutationResult SyntheticsSecureCredentialMutationResult `json:"SyntheticsCreateSecureCredential"`
}

const SyntheticsCreateSecureCredentialMutation = `mutation(
	$accountId: Int!,
	$description: String,
	$key: String!,
	$value: SecureValue!,
) { syntheticsCreateSecureCredential(
	accountId: $accountId,
	description: $description,
	key: $key,
	value: $value,
) {
	createdAt
	description
	errors {
		description
	}
	key
	lastUpdate
} }`

// Delete a Synthetics Private Location
func (a *Synthetics) SyntheticsDeletePrivateLocation(
	gUID EntityGUID,
) (*SyntheticsPrivateLocationDeleteResult, error) {
	return a.SyntheticsDeletePrivateLocationWithContext(context.Background(),
		gUID,
	)
}

// Delete a Synthetics Private Location
func (a *Synthetics) SyntheticsDeletePrivateLocationWithContext(
	ctx context.Context,
	gUID EntityGUID,
) (*SyntheticsPrivateLocationDeleteResult, error) {

	resp := SyntheticsDeletePrivateLocationQueryResponse{}
	vars := map[string]interface{}{
		"guid": gUID,
	}

	if err := a.client.NerdGraphQueryWithContext(ctx, SyntheticsDeletePrivateLocationMutation, vars, &resp); err != nil {
		return nil, err
	}

	return &resp.SyntheticsPrivateLocationDeleteResult, nil
}

type SyntheticsDeletePrivateLocationQueryResponse struct {
	SyntheticsPrivateLocationDeleteResult SyntheticsPrivateLocationDeleteResult `json:"SyntheticsDeletePrivateLocation"`
}

const SyntheticsDeletePrivateLocationMutation = `mutation(
	$guid: EntityGuid!,
) { syntheticsDeletePrivateLocation(
	guid: $guid,
) {
	errors {
		description
		type
	}
} }`

// Queues a request to delete an existing secure credential
func (a *Synthetics) SyntheticsDeleteSecureCredential(
	accountID int,
	key string,
) (*SyntheticsSecureCredentialMutationResult, error) {
	return a.SyntheticsDeleteSecureCredentialWithContext(context.Background(),
		accountID,
		key,
	)
}

// Queues a request to delete an existing secure credential
func (a *Synthetics) SyntheticsDeleteSecureCredentialWithContext(
	ctx context.Context,
	accountID int,
	key string,
) (*SyntheticsSecureCredentialMutationResult, error) {

	resp := SyntheticsDeleteSecureCredentialQueryResponse{}
	vars := map[string]interface{}{
		"accountId": accountID,
		"key":       key,
	}

	if err := a.client.NerdGraphQueryWithContext(ctx, SyntheticsDeleteSecureCredentialMutation, vars, &resp); err != nil {
		return nil, err
	}

	return &resp.SyntheticsSecureCredentialMutationResult, nil
}

type SyntheticsDeleteSecureCredentialQueryResponse struct {
	SyntheticsSecureCredentialMutationResult SyntheticsSecureCredentialMutationResult `json:"SyntheticsDeleteSecureCredential"`
}

const SyntheticsDeleteSecureCredentialMutation = `mutation(
	$accountId: Int!,
	$key: String!,
) { syntheticsDeleteSecureCredential(
	accountId: $accountId,
	key: $key,
) {
	createdAt
	description
	errors {
		description
	}
	key
	lastUpdate
} }`

// Purge the job queue for a specified private location
func (a *Synthetics) SyntheticsPurgePrivateLocationQueue(
	gUID EntityGUID,
) (*SyntheticsPrivateLocationPurgeQueueResult, error) {
	return a.SyntheticsPurgePrivateLocationQueueWithContext(context.Background(),
		gUID,
	)
}

// Purge the job queue for a specified private location
func (a *Synthetics) SyntheticsPurgePrivateLocationQueueWithContext(
	ctx context.Context,
	gUID EntityGUID,
) (*SyntheticsPrivateLocationPurgeQueueResult, error) {

	resp := SyntheticsPurgePrivateLocationQueueQueryResponse{}
	vars := map[string]interface{}{
		"guid": gUID,
	}

	if err := a.client.NerdGraphQueryWithContext(ctx, SyntheticsPurgePrivateLocationQueueMutation, vars, &resp); err != nil {
		return nil, err
	}

	return &resp.SyntheticsPrivateLocationPurgeQueueResult, nil
}

type SyntheticsPurgePrivateLocationQueueQueryResponse struct {
	SyntheticsPrivateLocationPurgeQueueResult SyntheticsPrivateLocationPurgeQueueResult `json:"SyntheticsPurgePrivateLocationQueue"`
}

const SyntheticsPurgePrivateLocationQueueMutation = `mutation(
	$guid: EntityGuid!,
) { syntheticsPurgePrivateLocationQueue(
	guid: $guid,
) {
	errors {
		description
		type
	}
} }`

// Update a Synthetics Private Location
func (a *Synthetics) SyntheticsUpdatePrivateLocation(
	description string,
	gUID EntityGUID,
	verifiedScriptExecution bool,
) (*SyntheticsPrivateLocationMutationResult, error) {
	return a.SyntheticsUpdatePrivateLocationWithContext(context.Background(),
		description,
		gUID,
		verifiedScriptExecution,
	)
}

// Update a Synthetics Private Location
func (a *Synthetics) SyntheticsUpdatePrivateLocationWithContext(
	ctx context.Context,
	description string,
	gUID EntityGUID,
	verifiedScriptExecution bool,
) (*SyntheticsPrivateLocationMutationResult, error) {

	resp := SyntheticsUpdatePrivateLocationQueryResponse{}
	vars := map[string]interface{}{
		"description":             description,
		"guid":                    gUID,
		"verifiedScriptExecution": verifiedScriptExecution,
	}

	if err := a.client.NerdGraphQueryWithContext(ctx, SyntheticsUpdatePrivateLocationMutation, vars, &resp); err != nil {
		return nil, err
	}

	return &resp.SyntheticsPrivateLocationMutationResult, nil
}

type SyntheticsUpdatePrivateLocationQueryResponse struct {
	SyntheticsPrivateLocationMutationResult SyntheticsPrivateLocationMutationResult `json:"SyntheticsUpdatePrivateLocation"`
}

const SyntheticsUpdatePrivateLocationMutation = `mutation(
	$description: String,
	$guid: EntityGuid!,
	$verifiedScriptExecution: Boolean,
) { syntheticsUpdatePrivateLocation(
	description: $description,
	guid: $guid,
	verifiedScriptExecution: $verifiedScriptExecution,
) {
	accountId
	description
	domainId
	errors {
		description
		type
	}
	guid
	key
	locationId
	name
	verifiedScriptExecution
} }`

// Queues a request to update an existing secure credential
func (a *Synthetics) SyntheticsUpdateSecureCredential(
	accountID int,
	description string,
	key string,
	value SecureValue,
) (*SyntheticsSecureCredentialMutationResult, error) {
	return a.SyntheticsUpdateSecureCredentialWithContext(context.Background(),
		accountID,
		description,
		key,
		value,
	)
}

// Queues a request to update an existing secure credential
func (a *Synthetics) SyntheticsUpdateSecureCredentialWithContext(
	ctx context.Context,
	accountID int,
	description string,
	key string,
	value SecureValue,
) (*SyntheticsSecureCredentialMutationResult, error) {

	resp := SyntheticsUpdateSecureCredentialQueryResponse{}
	vars := map[string]interface{}{
		"accountId":   accountID,
		"description": description,
		"key":         key,
		"value":       value,
	}

	if err := a.client.NerdGraphQueryWithContext(ctx, SyntheticsUpdateSecureCredentialMutation, vars, &resp); err != nil {
		return nil, err
	}

	return &resp.SyntheticsSecureCredentialMutationResult, nil
}

type SyntheticsUpdateSecureCredentialQueryResponse struct {
	SyntheticsSecureCredentialMutationResult SyntheticsSecureCredentialMutationResult `json:"SyntheticsUpdateSecureCredential"`
}

const SyntheticsUpdateSecureCredentialMutation = `mutation(
	$accountId: Int!,
	$description: String,
	$key: String!,
	$value: SecureValue,
) { syntheticsUpdateSecureCredential(
	accountId: $accountId,
	description: $description,
	key: $key,
	value: $value,
) {
	createdAt
	description
	errors {
		description
	}
	key
	lastUpdate
} }`
