// Code generated by tutone: DO NOT EDIT
package pathpoint

import "context"

// Creates a new Pathpoint flow with its associated stages, levels, steps, and signals.
func (a *Pathpoint) PathPointCreate(
	pathpoint PathPointFlowInput,
	scope PathPointScopeInput,
) (*PathPointFlowResult, error) {
	return a.PathPointCreateWithContext(context.Background(),
		pathpoint,
		scope,
	)
}

// Creates a new Pathpoint flow with its associated stages, levels, steps, and signals.
func (a *Pathpoint) PathPointCreateWithContext(
	ctx context.Context,
	pathpoint PathPointFlowInput,
	scope PathPointScopeInput,
) (*PathPointFlowResult, error) {

	resp := PathPointCreateQueryResponse{}
	vars := map[string]interface{}{
		"pathpoint": pathpoint,
		"scope":     scope,
	}

	if err := a.client.NerdGraphQueryWithContext(ctx, PathPointCreateMutation, vars, &resp); err != nil {
		return nil, err
	}

	return &resp.PathPointFlowResult, nil
}

type PathPointCreateQueryResponse struct {
	PathPointFlowResult PathPointFlowResult `json:"PathPointCreate"`
}

const PathPointCreateMutation = `mutation(
	$pathpoint: PathPointFlowInput!,
	$scope: PathPointScopeInput!,
) { pathPointCreate(
	pathpoint: $pathpoint,
	scope: $scope,
) {
	excludedKpis
	guid
	healthRollup
	healthStatus
	id
	kpis {
		accountId
		category
		description
		id
		name
		query {
			from
			select {
				aggregationType
				alias
				attribute
				threshold
			}
			timeWindow {
				customRange
				relativeRange {
					compareAgainst
					since
				}
			}
			where
		}
	}
	message
	metadata {
		createdAt
		createdBy {
			email
			gravatar
			id
			name
		}
		updatedAt
		updatedBy {
			email
			gravatar
			id
			name
		}
	}
	name
	refreshInterval
	stages {
		items {
			healthRollup
			healthStatus
			id
			isExcluded
			levels {
				items {
					healthStatus
					id
					steps {
						items {
							config {
								healthRollup
								thresholdType
								thresholdValue
							}
							entitySearchQuery {
								isExcluded
								query
							}
							healthStatus
							id
							isExcluded
							link
							name
							scopedAccounts
							signals {
								guid
								isExcluded
								name
								type
							}
						}
						nextCursor
						totalCount
					}
				}
				nextCursor
				totalCount
			}
			link
			name
			related {
				source
				target
			}
			stageKpis {
				accountId
				category
				description
				id
				name
				query {
					from
					select {
						aggregationType
						alias
						attribute
						threshold
					}
					timeWindow {
						customRange
						relativeRange {
							compareAgainst
							since
						}
					}
					where
				}
			}
		}
		nextCursor
		totalCount
	}
	version
} }`

// Deletes an existing Pathpoint flow and all associated workloads.
func (a *Pathpoint) PathPointDelete(
	gUID EntityGUID,
) (*PathPointDeleteResult, error) {
	return a.PathPointDeleteWithContext(context.Background(),
		gUID,
	)
}

// Deletes an existing Pathpoint flow and all associated workloads.
func (a *Pathpoint) PathPointDeleteWithContext(
	ctx context.Context,
	gUID EntityGUID,
) (*PathPointDeleteResult, error) {

	resp := PathPointDeleteQueryResponse{}
	vars := map[string]interface{}{
		"guid": gUID,
	}

	if err := a.client.NerdGraphQueryWithContext(ctx, PathPointDeleteMutation, vars, &resp); err != nil {
		return nil, err
	}

	return &resp.PathPointDeleteResult, nil
}

type PathPointDeleteQueryResponse struct {
	PathPointDeleteResult PathPointDeleteResult `json:"PathPointDelete"`
}

const PathPointDeleteMutation = `mutation(
	$guid: EntityGuid!,
) { pathPointDelete(
	guid: $guid,
) {
	guid
	name
} }`

// Updates an existing Pathpoint flow,
// entities with IDs are updated, entities without IDs are created,
// and entities present in the current entity guid but absent from the input are deleted.
func (a *Pathpoint) PathPointUpdate(
	gUID EntityGUID,
	pathpoint PathPointFlowUpdateInput,
) (*PathPointFlowResult, error) {
	return a.PathPointUpdateWithContext(context.Background(),
		gUID,
		pathpoint,
	)
}

// Updates an existing Pathpoint flow,
// entities with IDs are updated, entities without IDs are created,
// and entities present in the current entity guid but absent from the input are deleted.
func (a *Pathpoint) PathPointUpdateWithContext(
	ctx context.Context,
	gUID EntityGUID,
	pathpoint PathPointFlowUpdateInput,
) (*PathPointFlowResult, error) {

	resp := PathPointUpdateQueryResponse{}
	vars := map[string]interface{}{
		"guid":      gUID,
		"pathpoint": pathpoint,
	}

	if err := a.client.NerdGraphQueryWithContext(ctx, PathPointUpdateMutation, vars, &resp); err != nil {
		return nil, err
	}

	return &resp.PathPointFlowResult, nil
}

type PathPointUpdateQueryResponse struct {
	PathPointFlowResult PathPointFlowResult `json:"PathPointUpdate"`
}

const PathPointUpdateMutation = `mutation(
	$guid: EntityGuid!,
	$pathpoint: PathPointFlowUpdateInput!,
) { pathPointUpdate(
	guid: $guid,
	pathpoint: $pathpoint,
) {
	excludedKpis
	guid
	healthRollup
	healthStatus
	id
	kpis {
		accountId
		category
		description
		id
		name
		query {
			from
			select {
				aggregationType
				alias
				attribute
				threshold
			}
			timeWindow {
				customRange
				relativeRange {
					compareAgainst
					since
				}
			}
			where
		}
	}
	message
	metadata {
		createdAt
		createdBy {
			email
			gravatar
			id
			name
		}
		updatedAt
		updatedBy {
			email
			gravatar
			id
			name
		}
	}
	name
	refreshInterval
	stages {
		items {
			healthRollup
			healthStatus
			id
			isExcluded
			levels {
				items {
					healthStatus
					id
					steps {
						items {
							config {
								healthRollup
								thresholdType
								thresholdValue
							}
							entitySearchQuery {
								isExcluded
								query
							}
							healthStatus
							id
							isExcluded
							link
							name
							scopedAccounts
							signals {
								guid
								isExcluded
								name
								type
							}
						}
						nextCursor
						totalCount
					}
				}
				nextCursor
				totalCount
			}
			link
			name
			related {
				source
				target
			}
			stageKpis {
				accountId
				category
				description
				id
				name
				query {
					from
					select {
						aggregationType
						alias
						attribute
						threshold
					}
					timeWindow {
						customRange
						relativeRange {
							compareAgainst
							since
						}
					}
					where
				}
			}
		}
		nextCursor
		totalCount
	}
	version
} }`

// Fetches an existing Pathpoint flow by its entity GUID.
func (a *Pathpoint) GetFlow(
	accountID int,
	gUID EntityGUID,
) (*PathPointFlowResult, error) {
	return a.GetFlowWithContext(context.Background(),
		accountID,
		gUID,
	)
}

// Fetches an existing Pathpoint flow by its entity GUID.
func (a *Pathpoint) GetFlowWithContext(
	ctx context.Context,
	accountID int,
	gUID EntityGUID,
) (*PathPointFlowResult, error) {

	resp := flowResponse{}
	vars := map[string]interface{}{
		"accountID": accountID,
		"guid":      gUID,
	}

	if err := a.client.NerdGraphQueryWithContext(ctx, getFlowQuery, vars, &resp); err != nil {
		return nil, err
	}

	return &resp.Actor.Account.PathPoint.Flow, nil
}

const getFlowQuery = `query(
	$accountID: Int!,
	$guid: EntityGuid!,
) { actor { account(id: $accountID) { pathPoint { flow(
	guid: $guid,
) {
	excludedKpis
	guid
	healthRollup
	healthStatus
	id
	kpis {
		accountId
		category
		description
		id
		name
		query {
			from
			select {
				aggregationType
				alias
				attribute
				threshold
			}
			timeWindow {
				customRange
				relativeRange {
					compareAgainst
					since
				}
			}
			where
		}
	}
	message
	metadata {
		createdAt
		createdBy {
			email
			gravatar
			id
			name
		}
		updatedAt
		updatedBy {
			email
			gravatar
			id
			name
		}
	}
	name
	refreshInterval
	stages {
		items {
			healthRollup
			healthStatus
			id
			isExcluded
			levels {
				items {
					healthStatus
					id
					steps {
						items {
							config {
								healthRollup
								thresholdType
								thresholdValue
							}
							entitySearchQuery {
								isExcluded
								query
							}
							healthStatus
							id
							isExcluded
							link
							name
							scopedAccounts
							signals {
								guid
								isExcluded
								name
								type
							}
						}
						nextCursor
						totalCount
					}
				}
				nextCursor
				totalCount
			}
			link
			name
			related {
				source
				target
			}
			stageKpis {
				accountId
				category
				description
				id
				name
				query {
					from
					select {
						aggregationType
						alias
						attribute
						threshold
					}
					timeWindow {
						customRange
						relativeRange {
							compareAgainst
							since
						}
					}
					where
				}
			}
		}
		nextCursor
		totalCount
	}
	version
} } } } }`
