// Code NOT generated by tutone
package pathpoint

import (
	"encoding/json"
	"fmt"
)

// PathPointVersionMS is a version-control timestamp stored as epoch milliseconds.
// It is intentionally NOT based on nrtime.EpochMilliseconds because that type's
// MarshalJSON emits seconds for whole-second timestamps (e.g. 1722000000 instead
// of 1722000000000), which would cause version-conflict errors on every update.
// This type round-trips as a plain JSON integer, preserving exact milliseconds.
type PathPointVersionMS int64

func (v PathPointVersionMS) MarshalJSON() ([]byte, error) {
	return json.Marshal(int64(v))
}

func (v *PathPointVersionMS) UnmarshalJSON(b []byte) error {
	// Accept a JSON number
	var n int64
	if err := json.Unmarshal(b, &n); err == nil {
		*v = PathPointVersionMS(n)
		return nil
	}
	// Also accept a quoted string for defensive interop
	var s string
	if err := json.Unmarshal(b, &s); err == nil {
		var n2 int64
		if _, err2 := fmt.Sscanf(s, "%d", &n2); err2 == nil {
			*v = PathPointVersionMS(n2)
			return nil
		}
	}
	return fmt.Errorf("pathpoint: cannot unmarshal PathPointVersionMS from %s", b)
}
