version: "2"

# options for analysis running
run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m
  # exit code when at least one issue was found, default is 1
  issues-exit-code: 1
  # include test files or not, default is true
  tests: true



formatters:
  enable:
    - gofmt

linters:
  default: none
  enable:
    - errcheck
    - gocyclo
    - revive
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
  exclusions:
    rules:
       # We're needing to exclude these checks on types.go files, as the most affected linter check would be that
       # of gocyclo, for which an autogenerator creating a mere reflection of NerdGraph mutations and queries
       # as datatypes and unmarshal functions cannot counter the unintended cyclomatic complexity, or the misspelt
       # NerdGraph type definition/mutation comments. The linters shall be temporarily disabled on these files,
       # while they will still continue to scan through all _api.go and other test and utility files in the repository.
      - path: types.go
        linters:
          - gocyclo
          - govet
          - misspell

        # We're needing to exclude the revive check on files, as most files in the repository are autogenerated by Tutone
        # and accompany generated comments by Tutone from NerdGraph in the _api.go files but not against their types.
        # In order to have this linter enabled, a large scale Tutone generation change would be needed; which would then
        # allow us to have this linter run on selectively included files (which is why we've added this entry, instead of excluding the linter).
      - path: .go
        linters:
            - revive


  settings:
    govet:
      disable-all: true
      enable:
        - assign
        - bools
        - framepointer
        - shadow
        - stringintconv
        - structtag

    gocyclo:
      # minimal code complexity to report, 30 by default
      min-complexity: 25

    depguard:
      list-type: blacklist
      include-go-root: false
      packages:
        - github.com/davecgh/go-spew/spew

    # golint is deprecated in v2, hence not declared here

    lll:
      line-length: 150

    misspell:
      ignore-rules:
        - newrelic
    revive:
      rules:
        - name: exported
          severity: warning
          disabled: false
          arguments:
            - disableStutteringCheck

issues:
  # disable limits on issue reporting
  max-per-linter: 0
  max-same-issues: 0
