project_name: newrelic-client-go
env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download

build:
  skip: true

# Uses git-chglog output from release flow
changelog:
  skip: false

release:
  prerelease: false
  name_template: "{{.ProjectName}} v{{.Version}}"
