project_name: newrelic-client-go

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download

build:
  skip: true

release:
  # Mark as a pre-release for now
  prerelease: false
  name_template: "{{.ProjectName}} v{{.Version}}"

# Already using git-chglog
changelog:
  skip: true
