version: 2
project_name: newrelic-client-go
env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download

#build:

# Uses git-chglog output from release flow
changelog:
  disable: false

release:
  prerelease: false
  name_template: "{{.ProjectName}} v{{.Version}}"
