---
# Log level for running tutone
# Default: info
log_level: debug

# Cache for storing a GraphQL schema
cache:
  # Default: schema.json
  schema_file: schema.json

# GraphQL endpoint to query for schema
# Required
endpoint: https://api.newrelic.com/graphql

# How to authenticate to the API
auth:
  # Header set with the API key for authentication
  # Default: Api-Key
  header: Api-Key

  # Environment variable to get the API key from
  # Default: TUTONE_API_KEY
  api_key_env_var: NEW_RELIC_API_KEY

packages:
  - name: accounts
    path: pkg/accounts
    generators:
      - typegen
    imports:
      - github.com/newrelic/newrelic-client-go/internal/serialization
    types:
      - name: AccountOutline
      - name: AccountReference
      - name: EpochMilliseconds
        field_type_override: serialization.EpochTime
        skip_type_create: true
      - name: RegionScope

  - name: alerts
    path: pkg/alerts
    generators:
      - typegen
    types:
      - name: AlertsMutingRuleConditionInput
      - name: AlertsMutingRuleInput
      - name: AlertsMutingRuleScheduleInput
      - name: AlertsNrqlConditionTermsOperator
      - name: AlertsPoliciesSearchCriteriaInput
      - name: AlertsPoliciesSearchResultSet
      - name: AlertsPolicy
      - name: AlertsPolicyInput
      - name: AlertsPolicyUpdateInput
      - name: ID
        field_type_override: string
        skip_type_create: true
      - name: NaiveDateTime

  - name: apiaccess
    path: pkg/apiaccess
    generators:
      - typegen
    imports:
      - github.com/newrelic/newrelic-client-go/internal/serialization
    types:
      - name: ApiAccessActorStitchedFields
      - name: ApiAccessCreateIngestKeyInput
      - name: ApiAccessCreateInput
      - name: ApiAccessCreateKeyResponse
      - name: ApiAccessCreateUserKeyInput
      - name: ApiAccessDeleteInput
      - name: ApiAccessDeleteKeyResponse
      - name: ApiAccessIngestKeyErrorType
      - name: ApiAccessIngestKeyType
      - name: ApiAccessKey # gql interface
      - name: ApiAccessKeyError
      - name: ApiAccessKeySearchQuery
      - name: ApiAccessKeySearchResult
      - name: ApiAccessKeySearchScope
      - name: ApiAccessKeyType
      - name: ApiAccessUpdateIngestKeyInput
      - name: ApiAccessUpdateInput
      - name: ApiAccessUpdateKeyResponse
      - name: ApiAccessUpdateUserKeyInput
      - name: ApiAccessUserKeyErrorType
      - name: ID
        field_type_override: string
        skip_type_create: true

  - name: cloud
    path: pkg/cloud
    imports:
      - github.com/newrelic/newrelic-client-go/internal/serialization
      - encoding/json
      - fmt
    generators:
      - typegen
      - nerdgraphclient
    queries:
      - path: ["actor", "cloud"]
        endpoints:
          - name: linkedAccounts
            maxQueryFieldDepth: 2
    mutations:
      - name: cloudConfigureIntegration
      - name: cloudDisableIntegration
      - name: cloudLinkAccount
      - name: cloudRenameAccount
      - name: cloudUnlinkAccount
    types:
      - name: EpochSeconds
        field_type_override: serialization.EpochTime
        skip_type_create: true
      - name: EpochMilliseconds
        field_type_override: serialization.EpochTime
        skip_type_create: true

  - name: edge
    path: pkg/edge
    generators:
      - typegen
    types:
      - name: EdgeAccountStitchedFields
      - name: EdgeAgentEndpointDetail
      - name: EdgeCreateTraceObserverInput
      - name: EdgeCreateTraceObserverResponse
      - name: EdgeCreateTraceObserverResponseError
      - name: EdgeCreateTraceObserverResponseErrorType
      - name: EdgeCreateTraceObserverResponses
      - name: EdgeDeleteTraceObserverInput
      - name: EdgeDeleteTraceObserverResponse
      - name: EdgeDeleteTraceObserverResponseError
      - name: EdgeDeleteTraceObserverResponseErrorType
      - name: EdgeDeleteTraceObserverResponses
      - name: EdgeEndpoint
      - name: EdgeEndpointStatus
      - name: EdgeEndpointType
      - name: EdgeHttpsEndpointDetail
      - name: EdgeProviderRegion
      - name: EdgeTraceObserver
      - name: EdgeTraceObserverResponse
      - name: EdgeTraceObserverResponseError
      - name: EdgeTraceObserverResponseErrorType
      - name: EdgeTraceObserverStatus
      - name: EdgeTracing

  - name: eventstometrics
    path: pkg/eventstometrics
    generators:
      - typegen
    types:
      - name: EventsToMetricsAccountStitchedFields
      - name: EventsToMetricsCreateRuleFailure
      - name: EventsToMetricsCreateRuleInput
      - name: EventsToMetricsCreateRuleResult
      - name: EventsToMetricsCreateRuleSubmission
      - name: EventsToMetricsDeleteRuleFailure
      - name: EventsToMetricsDeleteRuleInput
      - name: EventsToMetricsDeleteRuleResult
      - name: EventsToMetricsDeleteRuleSubmission
      - name: EventsToMetricsErrorReason
      - name: EventsToMetricsListRuleResult
      - name: EventsToMetricsRule
      - name: EventsToMetricsUpdateRuleFailure
      - name: EventsToMetricsUpdateRuleInput
      - name: EventsToMetricsUpdateRuleResult
      - name: EventsToMetricsUpdateRuleSubmission
      - name: ID
        field_type_override: string
        create_as: string
        skip_type_create: false
      - name: RuleId
        field_type_override: string

  - name: nrdb
    path: pkg/nrdb
    generators:
      - typegen
    imports:
      - github.com/newrelic/newrelic-client-go/internal/serialization
    types:
      - name: EpochSeconds
        create_as: serialization.EpochTime
      - name: EpochMilliseconds
        create_as: serialization.EpochTime
      - name: Nrql
        create_as: string
      - name: NRDBMetadataTimeWindow
      - name: NRDBResult
        create_as: map[string]interface{}
      - name: NrqlHistoricalQuery
      - name: SuggestedNRQLQuery
      - name: NrdbResultContainer

generators:
  - name: typegen
    fileName: "types.go"
  - name: nerdgraphclient
    fileName: "{{.PackageName}}_api.go"
