---
# Log level for running tutone
# Default: info
log_level: debug

# File to store a copy of the schema
# Default: schema.json
schema_file: schema.json

# GraphQL endpoint to query for schema
# Required
endpoint: https://api.newrelic.com/graphql

# How to authenticate to the API
auth:
  # Header set with the API key for authentication
  # Default: Api-Key
  header: Api-Key

  # Environment variable to get the API key from
  # Default: TUTONE_API_KEY
  api-key-env: NEW_RELIC_API_KEY

packages:
  - name: alerts
    path: pkg/alerts
    generators:
      - typegen
    types:
      - name: AlertsMutingRuleConditionInput
      - name: AlertsMutingRuleInput
      - name: AlertsPoliciesSearchCriteriaInput
      - name: AlertsPoliciesSearchResultSet
      - name: AlertsPolicy
      - name: AlertsPolicyInput
      - name: AlertsPolicyUpdateInput
      - name: AlertsNrqlConditionTermsOperator
      - name: ID
        field_type_override: string
        skip_type_create: true
  - name: edge
    path: pkg/edge
    generators:
      - typegen
    types:
      - name: EdgeAccountStitchedFields
      - name: EdgeAgentEndpointDetail
      - name: EdgeCreateTraceObserverInput
      - name: EdgeCreateTraceObserverResponse
      - name: EdgeCreateTraceObserverResponseError
      - name: EdgeCreateTraceObserverResponseErrorType
      - name: EdgeCreateTraceObserverResponses
      - name: EdgeDeleteTraceObserverInput
      - name: EdgeDeleteTraceObserverResponse
      - name: EdgeDeleteTraceObserverResponseError
      - name: EdgeDeleteTraceObserverResponseErrorType
      - name: EdgeDeleteTraceObserverResponses
      - name: EdgeEndpoint
      - name: EdgeEndpointType
      - name: EdgeEndpointStatus
      - name: EdgeHttpsEndpointDetail
      - name: EdgeProviderRegion
      - name: EdgeTraceObserver
      - name: EdgeTraceObserverResponse
      - name: EdgeTraceObserverResponseError
      - name: EdgeTraceObserverResponseErrorType
      - name: EdgeTraceObserverStatus
      - name: EdgeTracing
  - name: accounts
    path: pkg/accounts
    generators:
      - typegen
    types:
      - name: AccountOutline
      - name: RegionScope
  - name: eventstometrics
    path: pkg/eventstometrics
    generators:
      - typegen
    types:
      - name: EventsToMetricsAccountStitchedFields
      - name: EventsToMetricsCreateRuleFailure
      - name: EventsToMetricsCreateRuleInput
      - name: EventsToMetricsCreateRuleResult
      - name: EventsToMetricsCreateRuleSubmission
      - name: EventsToMetricsDeleteRuleFailure
      - name: EventsToMetricsDeleteRuleInput
      - name: EventsToMetricsDeleteRuleResult
      - name: EventsToMetricsDeleteRuleSubmission
      - name: EventsToMetricsErrorReason
      - name: EventsToMetricsListRuleResult
      - name: EventsToMetricsRule
      - name: EventsToMetricsUpdateRuleFailure
      - name: EventsToMetricsUpdateRuleInput
      - name: EventsToMetricsUpdateRuleResult
      - name: EventsToMetricsUpdateRuleSubmission
      - name: RuleId
        field_type_override: string
      - name: ID
        field_type_override: string
        create_as: string
        skip_type_create: false
  - name: nrdb
    path: pkg/nrdb
    generators:
      - typegen
    imports:
      - github.com/newrelic/newrelic-client-go/internal/serialization
    types:
      - name: EpochSeconds
        create_as: serialization.EpochTime
      - name: EpochMilliseconds
        create_as: serialization.EpochTime
      - name: Nrql
        create_as: string
      - name: NrdbResult
        create_as: map[string]interface{}
      - name: NrdbResultContainer
      - name: NrqlHistoricalQuery
      - name: SuggestedNrqlQuery
      - name: NrdbMetadataTimeWindow


generators:
  - name: typegen
    fileName: "types.go"
