// Code generated by tutone: DO NOT EDIT
package applicationsettings

import "context"

// Update configuration for APM applications. Includes thresholds for how often to record Transaction traces, SQL traces, enabling Distributed traces, ignoring certain error classes. This is the main mutation that powers the Application > Settings page in APM.
func (a *ApplicationSettings) AgentApplicationSettingsUpdate(
	gUID EntityGUID,
	settings AgentApplicationSettingsUpdateInput,
) (*AgentApplicationSettingsUpdateResult, error) {
	return a.AgentApplicationSettingsUpdateWithContext(context.Background(),
		gUID,
		settings,
	)
}

// Update configuration for APM applications. Includes thresholds for how often to record Transaction traces, SQL traces, enabling Distributed traces, ignoring certain error classes. This is the main mutation that powers the Application > Settings page in APM.
func (a *ApplicationSettings) AgentApplicationSettingsUpdateWithContext(
	ctx context.Context,
	gUID EntityGUID,
	settings AgentApplicationSettingsUpdateInput,
) (*AgentApplicationSettingsUpdateResult, error) {

	resp := AgentApplicationSettingsUpdateQueryResponse{}
	vars := map[string]interface{}{
		"guid":     gUID,
		"settings": settings,
	}

	if err := a.client.NerdGraphQueryWithContext(ctx, AgentApplicationSettingsUpdateMutation, vars, &resp); err != nil {
		return nil, err
	}

	return &resp.AgentApplicationSettingsUpdateResult, nil
}

type AgentApplicationSettingsUpdateQueryResponse struct {
	AgentApplicationSettingsUpdateResult AgentApplicationSettingsUpdateResult `json:"AgentApplicationSettingsUpdate"`
}

const AgentApplicationSettingsUpdateMutation = `mutation(
	$guid: EntityGuid!,
	$settings: AgentApplicationSettingsUpdateInput!,
) { agentApplicationSettingsUpdate(
	guid: $guid,
	settings: $settings,
) {
	alias
	apmSettings {
		alias
		apmConfig {
			apdexTarget
			useServerSideConfig
		}
		applicationLogging {
			enabled
			forwarding {
				enabled
				maxSamplesStored
			}
			localDecorating {
				enabled
			}
			metrics {
				enabled
			}
		}
		captureMemcacheKeys
		errorCollector {
			enabled
			expectedErrorClasses
			expectedErrorCodes
			ignoredErrorClasses
			ignoredErrorCodes
		}
		jfr {
			enabled
		}
		originalName
		slowSql {
			enabled
		}
		threadProfiler {
			enabled
		}
		tracerType
		transactionTracer {
			captureMemcacheKeys
			enabled
			explainEnabled
			explainThresholdType
			explainThresholdValue
			logSql
			recordSql
			stackTraceThreshold
			transactionThresholdType
			transactionThresholdValue
		}
	}
	applicationLogging {
		enabled
		forwarding {
			enabled
			maxSamplesStored
		}
		localDecorating {
			enabled
		}
		metrics {
			enabled
		}
	}
	browserProperties {
		jsConfig
		jsConfigScript
		jsLoaderScript
	}
	browserSettings {
		browserConfig {
			apdexTarget
		}
		browserMonitoring {
			ajax {
				denyList
			}
			distributedTracing {
				allowedOrigins
				corsEnabled
				corsUseNewrelicHeader
				corsUseTracecontextHeaders
				enabled
				excludeNewrelicHeader
			}
			loader
			pinnedVersion
			privacy {
				cookiesEnabled
			}
		}
		sessionReplay {
			autoStart
			blockSelector
			collectFonts
			enabled
			errorSamplingRate
			inlineImages
			inlineStylesheet
			maskAllInputs
			maskInputOptions {
				color
				date
				datetimeLocal
				email
				month
				number
				range
				search
				select
				tel
				text
				textArea
				time
				url
				week
			}
			maskTextSelector
			samplingRate
		}
		sessionTrace {
			enabled
			errorSamplingRate
			mode
			samplingRate
		}
	}
	errors {
		description
		errorClass
		field
	}
	guid
	mobileSettings {
		applicationExitInfo {
			enabled
		}
		networkSettings {
			aliases {
				alias
				hosts
			}
			filterMode
			hideList
			ignoredStatusCodeRules {
				hosts
				statusCodes
			}
			showList
		}
		useCrashReports
	}
	name
} }`
