// Code generated by tutone: DO NOT EDIT
package accounts

import (
	"github.com/newrelic/newrelic-client-go/internal/serialization"
)

// RegionScope -
type RegionScope string

var RegionScopeTypes = struct {
	// Do not filter by region
	GLOBAL RegionScope
	// Filter by region
	IN_REGION RegionScope
}{
	// Do not filter by region
	GLOBAL: "GLOBAL",
	// Filter by region
	IN_REGION: "IN_REGION",
}

// AccountOutline - The `AccountOutline` object provides basic data about an account.
type AccountOutline struct {
	//
	ID int `json:"id"`
	//
	Name string `json:"name"`
	// Returns event types that are currently reporting in the account.
	ReportingEventTypes []string `json:"reportingEventTypes"`
}

// TimeWindowInput - Represents a time window input.
type TimeWindowInput struct {
	// The end time of the time window the number of milliseconds since the Unix epoch.
	EndTime serialization.EpochTime `json:"endTime"`
	// The start time of the time window the number of milliseconds since the Unix epoch.
	StartTime serialization.EpochTime `json:"startTime"`
}
