// Code generated by tutone: DO NOT EDIT
package streamingexport

import (
	"context"

	"github.com/newrelic/newrelic-client-go/v2/pkg/errors"
)

// Create new streaming rule
func (a *Streamingexport) StreamingExportCreateRule(
	accountID int,
	awsParameters StreamingExportAwsInput,
	azureParameters StreamingExportAzureInput,
	gcpParameters StreamingExportGcpInput,
	ruleParameters StreamingExportRuleInput,
) (*StreamingExportRule, error) {
	return a.StreamingExportCreateRuleWithContext(context.Background(),
		accountID,
		awsParameters,
		azureParameters,
		gcpParameters,
		ruleParameters,
	)
}

// Create new streaming rule
func (a *Streamingexport) StreamingExportCreateRuleWithContext(
	ctx context.Context,
	accountID int,
	awsParameters StreamingExportAwsInput,
	azureParameters StreamingExportAzureInput,
	gcpParameters StreamingExportGcpInput,
	ruleParameters StreamingExportRuleInput,
) (*StreamingExportRule, error) {

	resp := StreamingExportCreateRuleQueryResponse{}
	vars := map[string]interface{}{
		"accountId":       accountID,
		"awsParameters":   awsParameters,
		"azureParameters": azureParameters,
		"gcpParameters":   gcpParameters,
		"ruleParameters":  ruleParameters,
	}

	if err := a.client.NerdGraphQueryWithContext(ctx, StreamingExportCreateRuleMutation, vars, &resp); err != nil {
		return nil, err
	}

	return &resp.StreamingExportRule, nil
}

type StreamingExportCreateRuleQueryResponse struct {
	StreamingExportRule StreamingExportRule `json:"StreamingExportCreateRule"`
}

const StreamingExportCreateRuleMutation = `mutation(
	$accountId: Int!,
	$awsParameters: StreamingExportAwsInput,
	$azureParameters: StreamingExportAzureInput,
	$gcpParameters: StreamingExportGcpInput,
	$ruleParameters: StreamingExportRuleInput!,
) { streamingExportCreateRule(
	accountId: $accountId,
	awsParameters: $awsParameters,
	azureParameters: $azureParameters,
	gcpParameters: $gcpParameters,
	ruleParameters: $ruleParameters,
) {
	account {
		id
		name
	}
	aws {
		awsAccountId
		deliveryStreamName
		region
		role
	}
	azure {
		eventHubConnectionString
		eventHubName
	}
	createdAt
	description
	gcp {
		gcpProjectId
		pubsubTopicId
	}
	id
	message
	name
	nrql
	payloadCompression
	status
	updatedAt
} }`

// List the streaming rules for the given account
func (a *Streamingexport) GetStreamingRules(
	accountID int,
) (*[]StreamingExportRule, error) {
	return a.GetStreamingRulesWithContext(context.Background(),
		accountID,
	)
}

// List the streaming rules for the given account
func (a *Streamingexport) GetStreamingRulesWithContext(
	ctx context.Context,
	accountID int,
) (*[]StreamingExportRule, error) {

	resp := streamingRulesResponse{}
	vars := map[string]interface{}{
		"accountID": accountID,
	}

	if err := a.client.NerdGraphQueryWithContext(ctx, getStreamingRulesQuery, vars, &resp); err != nil {
		return nil, err
	}

	if len(resp.Actor.Account.StreamingExport.StreamingRules) == 0 {
		return nil, errors.NewNotFound("")
	}

	return &resp.Actor.Account.StreamingExport.StreamingRules, nil
}

const getStreamingRulesQuery = `query(
	$accountID: Int!,
) { actor { account(id: $accountID) { streamingExport { streamingRules {
	account {
		id
		name
	}
	aws {
		awsAccountId
		deliveryStreamName
		region
		role
	}
	azure {
		eventHubConnectionString
		eventHubName
	}
	createdAt
	description
	gcp {
		gcpProjectId
		pubsubTopicId
	}
	id
	message
	name
	nrql
	payloadCompression
	status
	updatedAt
} } } } }`
