// Code generated by tutone: DO NOT EDIT
package streamingexport

// StreamingExportPayloadCompression - Whether Compression is enabled for the export rule, and what compression format is used
type StreamingExportPayloadCompression string

var StreamingExportPayloadCompressionTypes = struct {
	// Do not compress payloads for this export rule
	DISABLED StreamingExportPayloadCompression
	// Compress payloads for this export rule using the GZIP compression format
	GZIP StreamingExportPayloadCompression
}{
	// Do not compress payloads for this export rule
	DISABLED: "DISABLED",
	// Compress payloads for this export rule using the GZIP compression format
	GZIP: "GZIP",
}

// StreamingExportStatus - Set of streaming rules states
type StreamingExportStatus string

var StreamingExportStatusTypes = struct {
	// Status set for a streaming rule that could not be created due to an error
	CREATION_FAILED StreamingExportStatus
	// Status set for a streaming rule being set up
	CREATION_IN_PROGRESS StreamingExportStatus
	// Status set for a streaming rule when it is deleted
	DELETED StreamingExportStatus
	// Status set for a streaming rule when it is disabled
	DISABLED StreamingExportStatus
	// Status set for a streaming rule when it is enabled
	ENABLED StreamingExportStatus
}{
	// Status set for a streaming rule that could not be created due to an error
	CREATION_FAILED: "CREATION_FAILED",
	// Status set for a streaming rule being set up
	CREATION_IN_PROGRESS: "CREATION_IN_PROGRESS",
	// Status set for a streaming rule when it is deleted
	DELETED: "DELETED",
	// Status set for a streaming rule when it is disabled
	DISABLED: "DISABLED",
	// Status set for a streaming rule when it is enabled
	ENABLED: "ENABLED",
}

// Account - The `Account` object provides general data about the account, as well as
// being the entry point into more detailed data about a single account.
//
// Account configuration data is queried through this object, as well as
// telemetry data that is specific to a single account.
type Account struct {
	ID         int    `json:"id,omitempty"`
	LicenseKey string `json:"licenseKey,omitempty"`
	Name       string `json:"name,omitempty"`
	// This field provides access to StreamingExport data.
	StreamingExport StreamingExportAccountStitchedFields `json:"streamingExport,omitempty"`
}

// AccountReference - The `AccountReference` object provides basic identifying information about the account.
type AccountReference struct {
	ID   int    `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
}

// Actor - The `Actor` object contains fields that are scoped to the API user's access level.
type Actor struct {
	// The `account` field is the entry point into data that is scoped to a single account.
	Account Account `json:"account,omitempty"`
}

type StreamingExportAccountStitchedFields struct {
	// Get the information for a specific streaming rule
	StreamingRule StreamingExportRule `json:"streamingRule,omitempty"`
	// List the streaming rules for the given account
	StreamingRules []StreamingExportRule `json:"streamingRules,omitempty"`
}

// StreamingExportAwsDetails - AWS details about a streaming rule
type StreamingExportAwsDetails struct {
	// The AWS account to which the target firehose belongs
	AwsAccountId int `json:"awsAccountId"`
	// The name of the delivery stream to write events to
	DeliveryStreamName string `json:"deliveryStreamName"`
	// The AWS region the delivery stream is located in
	Region string `json:"region"`
	// The role configured for New Relic to assume
	Role string `json:"role"`
}

// StreamingExportAwsInput - AWS input parameters for a new streaming rule
type StreamingExportAwsInput struct {
	// The AWS account to which the target firehose belongs
	AwsAccountId int `json:"awsAccountId"`
	// The name of the delivery stream to write events to
	DeliveryStreamName string `json:"deliveryStreamName"`
	// The AWS region the delivery stream is located in
	Region string `json:"region"`
	// The role configured for New Relic to assume
	Role string `json:"role"`
}

// StreamingExportAzureDetails - Azure details about a streaming rule
type StreamingExportAzureDetails struct {
	// Connection string that has access to the specific Event Hub
	EventHubConnectionString string `json:"eventHubConnectionString"`
	// The name of Event Hub to write events to
	EventHubName string `json:"eventHubName"`
}

// StreamingExportAzureInput - Azure input parameters for a new streaming rule
type StreamingExportAzureInput struct {
	// Connection string that has access to the specific Event Hub
	EventHubConnectionString string `json:"eventHubConnectionString"`
	// The name of Event Hub to write events to
	EventHubName string `json:"eventHubName"`
}

// StreamingExportGcpDetails - GCP details parameters for a new streaming rule
type StreamingExportGcpDetails struct {
	// gcp project id
	GcpProjectId string `json:"gcpProjectId"`
	// pub sub topic id
	PubsubTopicId string `json:"pubsubTopicId"`
}

// StreamingExportGcpInput - GCP input parameters for a new streaming rule
type StreamingExportGcpInput struct {
	// gcp project id
	GcpProjectId string `json:"gcpProjectId"`
	// pub sub topic id
	PubsubTopicId string `json:"pubsubTopicId"`
}

// StreamingExportRule - Details about a streaming rule
type StreamingExportRule struct {
	// The account associated to this streaming rule
	Account AccountReference `json:"account,omitempty"`
	// The AWS information configured for the streaming rule
	Aws StreamingExportAwsDetails `json:"aws,omitempty"`
	// The Azure information configured for the streaming rule
	Azure StreamingExportAzureDetails `json:"azure,omitempty"`
	// The time at which the process of creating the streaming rule began
	CreatedAt EpochMilliseconds `json:"createdAt"`
	// Additional information about the streaming rule
	Description string `json:"description,omitempty"`
	// The GCP information configured for the streaming rule
	Gcp StreamingExportGcpDetails `json:"gcp,omitempty"`
	// The rule ID for this streaming rule
	ID int `json:"id"`
	// A message returned by the latest API call
	Message string `json:"message,omitempty"`
	// NRQL used to select data to be exported
	NRQL NRQL `json:"nrql,omitempty"`
	// The name of this streaming rule
	Name string `json:"name"`
	// Whether or not to compress payloads before exporting them, and what compression format to use if so
	PayloadCompression StreamingExportPayloadCompression `json:"payloadCompression,omitempty"`
	// The state of this streaming rule
	Status StreamingExportStatus `json:"status"`
	// The last time the status of the streaming rule was updated
	UpdatedAt EpochMilliseconds `json:"updatedAt"`
}

// StreamingExportRuleInput - The input parameters for a new streaming rule
type StreamingExportRuleInput struct {
	// Additional information about the rule
	Description string `json:"description,omitempty"`
	// NRQL to select the telemetry data to export
	NRQL NRQL `json:"nrql"`
	// The name of this export rule
	Name string `json:"name"`
	// Whether to compress payloads before sending them out, and what compression format to use if enabled
	PayloadCompression StreamingExportPayloadCompression `json:"payloadCompression,omitempty"`
}

type streamingRulesResponse struct {
	Actor Actor `json:"actor"`
}

// EpochMilliseconds - The `EpochMilliseconds` scalar represents the number of milliseconds since the Unix epoch
type EpochMilliseconds string

// ID - The `ID` scalar type represents a unique identifier, often used to
// refetch an object or as key for a cache. The ID type appears in a JSON
// response as a String; however, it is not intended to be human-readable.
// When expected as an input type, any string (such as `"4"`) or integer
// (such as `4`) input value will be accepted as an ID.
type ID string

// NRQL - This scalar represents a NRQL query string.
//
// See the [NRQL Docs](https://docs.newrelic.com/docs/insights/nrql-new-relic-query-language/nrql-resources/nrql-syntax-components-functions) for more information about NRQL syntax.
type NRQL string
