// Package notebooks manages New Relic Notebook entities.
//
// The Notebook API is split across two backends and this package hides that
// split behind a single client:
//
//   - Notebook CONTENT (the JSON block/widget tree that renders in the UI, plus
//     the notebook's name at create time and renames afterwards) is served by
//     the Blob Storage API at https://blob-api.service.newrelic.com/v1/e over
//     plain HTTP with the User API key. Those calls live in
//     notebooks_blob.go.
//
//   - Notebook METADATA (tags, scope, entity version, created/updated actors)
//     is queried through NerdGraph's actor.entityManagement namespace. Those
//     helpers plus a generic entityManagementDelete mutation are generated by
//     tutone into notebooks_api.go and types.go.
//
// For the public documentation on Notebooks and the Blob Storage API, see:
// https://docs.newrelic.com/docs/query-your-data/explore-query-data/notebooks/
package notebooks

import (
	"github.com/newrelic/newrelic-client-go/v2/internal/http"
	"github.com/newrelic/newrelic-client-go/v2/pkg/config"
	"github.com/newrelic/newrelic-client-go/v2/pkg/logging"
)

// Notebooks is the client for the New Relic Notebooks APIs.
type Notebooks struct {
	client http.Client
	config config.Config
	logger logging.Logger
}

// New returns a new Notebooks client. It uses the same authentication and
// transport configuration as every other package in newrelic-client-go - the
// User API key on `config.PersonalAPIKey` is sent as `Api-Key` on both the
// NerdGraph and Blob Storage endpoints.
func New(cfg config.Config) Notebooks {
	client := http.NewClient(cfg)
	client.SetAuthStrategy(&http.PersonalAPIKeyCapableV2Authorizer{})

	return Notebooks{
		client: client,
		config: cfg,
		logger: cfg.GetLogger(),
	}
}
