// Code generated by tutone: DO NOT EDIT
package fleetcontrol

import (
	"github.com/newrelic/newrelic-client-go/v2/pkg/nrtime"
)

// FleetControlEntityScope - The list of possible scopes of an entity
type FleetControlEntityScope string

var FleetControlEntityScopeTypes = struct {
	// Account scope
	ACCOUNT FleetControlEntityScope
	// Organization scope
	ORGANIZATION FleetControlEntityScope
}{
	// Account scope
	ACCOUNT: "ACCOUNT",
	// Organization scope
	ORGANIZATION: "ORGANIZATION",
}

// FleetControlFleetDeploymentPhase - Phases of a fleet deployment
type FleetControlFleetDeploymentPhase string

var FleetControlFleetDeploymentPhaseTypes = struct {
	// Deployment completed
	COMPLETED FleetControlFleetDeploymentPhase
	// Deployment is in editable phase
	CREATED FleetControlFleetDeploymentPhase
	// Deployment failed
	FAILED FleetControlFleetDeploymentPhase
	// Deployment is in progress
	IN_PROGRESS FleetControlFleetDeploymentPhase
}{
	// Deployment completed
	COMPLETED: "COMPLETED",
	// Deployment is in editable phase
	CREATED: "CREATED",
	// Deployment failed
	FAILED: "FAILED",
	// Deployment is in progress
	IN_PROGRESS: "IN_PROGRESS",
}

// FleetControlManagedEntityType - Entity types that a Fleet can manage
type FleetControlManagedEntityType string

var FleetControlManagedEntityTypeTypes = struct {
	// Instrumented APM Application
	APPLICATION FleetControlManagedEntityType
	// Infra Host
	HOST FleetControlManagedEntityType
	// Kubernetes Cluster
	KUBERNETESCLUSTER FleetControlManagedEntityType
}{
	// Instrumented APM Application
	APPLICATION: "APPLICATION",
	// Infra Host
	HOST: "HOST",
	// Kubernetes Cluster
	KUBERNETESCLUSTER: "KUBERNETESCLUSTER",
}

// FleetControlActor - Represents an actor
type FleetControlActor struct {
	// Id of the actor
	ID string `json:"id"`
}

// FleetControlCollectionEntity - Entity type to represent collections of entities
type FleetControlCollectionEntity struct {
	// The collection entity id
	ID string `json:"id"`
	// Metadata about the entity
	Metadata FleetControlMetadata `json:"metadata"`
	// The name of this entity
	Name string `json:"name"`
	// The entity's scope
	Scope FleetControlScopedReference `json:"scope"`
	// Collection of tags
	Tags []FleetControlTag `json:"tags"`
	// The entity type
	Type string `json:"type"`
}

// FleetControlConfigurationVersionList - Properties of a configuration version
type FleetControlConfigurationVersionList struct {
	// Configuration version id
	ID string `json:"id"`
}

// FleetControlConfigurationVersionListInput - Configuration version list input
type FleetControlConfigurationVersionListInput struct {
	// Configuration version id
	ID string `json:"id"`
}

// FleetControlCreateFleetResult - The result of creating a fleet
type FleetControlCreateFleetResult struct {
	// The created fleet entity
	Entity FleetControlFleetEntityResult `json:"entity"`
}

// FleetControlDeleteFleetResult - The result returned when deleting a fleet
type FleetControlDeleteFleetResult struct {
	// Fleet entity id
	ID string `json:"id"`
}

// FleetControlFleetDeploymentCreateInput - Fleet deployment create input
type FleetControlFleetDeploymentCreateInput struct {
	// Fleet deployment configuration version list
	ConfigurationVersionList []FleetControlConfigurationVersionListInput `json:"configurationVersionList,omitempty"`
	// Fleet deployment description
	Description string `json:"description,omitempty"`
	// Fleet entity id
	FleetId string `json:"fleetId"`
	// Fleet deployment name
	Name string `json:"name,omitempty"`
	// Entity scope
	Scope FleetControlScopedReferenceInput `json:"scope,omitempty"`
	// Fleet deployment tags
	Tags []FleetControlTagInput `json:"tags,omitempty"`
}

// FleetControlFleetDeploymentCreateResult - The result of creating a fleet deployment
type FleetControlFleetDeploymentCreateResult struct {
	// The created entity
	Entity FleetControlFleetDeploymentResult `json:"entity"`
}

// FleetControlFleetDeploymentDeleteResult - The result of deleting a fleet deployment
type FleetControlFleetDeploymentDeleteResult struct {
	// Fleet deployment entity id
	ID string `json:"id"`
}

// FleetControlFleetDeploymentResult - The result returned for a fleet deployment
type FleetControlFleetDeploymentResult struct {
	// Fleet deployment configuration version list
	ConfigurationVersionList []FleetControlConfigurationVersionList `json:"configurationVersionList,omitempty"`
	// Fleet deployment description
	Description string `json:"description,omitempty"`
	// Fleet entity id
	FleetId string `json:"fleetId"`
	// Fleet deployment entity id
	ID string `json:"id"`
	// Metadata about the entity
	Metadata FleetControlMetadata `json:"metadata"`
	// Fleet deployment name
	Name string `json:"name,omitempty"`
	// Fleet deployment phase
	Phase FleetControlFleetDeploymentPhase `json:"phase,omitempty"`
	// Fleet deployment ring tracker
	RingsDeploymentTracker []FleetControlRingsDeploymentTracker `json:"ringsDeploymentTracker,omitempty"`
	// The entity's scope
	Scope FleetControlScopedReference `json:"scope"`
	// The fleet deployment tags
	Tags []FleetControlTag `json:"tags"`
	// The entity type
	Type string `json:"type"`
}

// FleetControlFleetDeploymentUpdateInput - Fleet deployment update input
type FleetControlFleetDeploymentUpdateInput struct {
	// Fleet deployment configuration version list
	ConfigurationVersionList []FleetControlConfigurationVersionListInput `json:"configurationVersionList,omitempty"`
	// Fleet deployment description
	Description string `json:"description,omitempty"`
	// Fleet deployment name
	Name string `json:"name,omitempty"`
	// Fleet deployment tags
	Tags []FleetControlTagInput `json:"tags,omitempty"`
}

// FleetControlFleetDeploymentUpdateResult - The result of updating a fleet deployment
type FleetControlFleetDeploymentUpdateResult struct {
	// The updated entity
	Entity FleetControlFleetDeploymentResult `json:"entity"`
}

// FleetControlFleetEntityCreateInput - Fleet entity create input
type FleetControlFleetEntityCreateInput struct {
	// The fleet entity description
	Description string `json:"description,omitempty"`
	// The type of entity the fleet will manage
	ManagedEntityType FleetControlManagedEntityType `json:"managedEntityType"`
	// The fleet entity name
	Name string `json:"name"`
	// The fleet specific product type
	Product string `json:"product,omitempty"`
	// The entity scope
	Scope FleetControlScopedReferenceInput `json:"scope,omitempty"`
	// The fleet entity tags
	Tags []FleetControlTagInput `json:"tags,omitempty"`
}

// FleetControlFleetEntityResult - The result returned for an updated fleet entity
type FleetControlFleetEntityResult struct {
	// Fleet entity description
	Description string `json:"description,omitempty"`
	// Fleet entity id
	ID string `json:"id"`
	// Associates rings of managed entities for the fleet
	ManagedEntityRings FleetControlCollectionEntity `json:"managedEntityRings,omitempty"`
	// Type of entity the fleet will manage
	ManagedEntityType FleetControlManagedEntityType `json:"managedEntityType"`
	// Metadata about the entity
	Metadata FleetControlMetadata `json:"metadata"`
	// Fleet entity name
	Name string `json:"name"`
	// Fleet specific product type
	Product []string `json:"product"`
	// Fleet entity scope
	Scope FleetControlScopedReference `json:"scope"`
	// Fleet entity tags
	Tags []FleetControlTag `json:"tags"`
	// Fleet entity type
	Type string `json:"type"`
}

// FleetControlFleetMemberRing - The ring to modify entities
type FleetControlFleetMemberRing struct {
	// The list of entityIds modified on the fleet
	EntityIds []string `json:"entityIds"`
	// The ring name to modify entities
	Ring string `json:"ring"`
}

// FleetControlFleetMemberRingInput - The ring to modify entities
type FleetControlFleetMemberRingInput struct {
	// The list of entityIds to modify on the fleet
	EntityIds []string `json:"entityIds"`
	// The ring name to modify entities
	Ring string `json:"ring"`
}

// FleetControlFleetMembersResult - The result returned when modifying managed entities on a fleet
type FleetControlFleetMembersResult struct {
	// The fleet entity id
	FleetId string `json:"fleetId"`
	// The list of modified managed entities on a fleet ring
	Members []FleetControlFleetMemberRing `json:"members"`
}

// FleetControlMetadata - Metadata of an entity
type FleetControlMetadata struct {
	// The entity's creation time
	CreatedAt nrtime.EpochMilliseconds `json:"createdAt,omitempty"`
	// Actor that created this entity
	CreatedBy FleetControlActor `json:"createdBy,omitempty"`
	// The entity's last update time
	UpdatedAt nrtime.EpochMilliseconds `json:"updatedAt,omitempty"`
	// Actor that updated this entity
	UpdatedBy FleetControlActor `json:"updatedBy,omitempty"`
}

// FleetControlRingsDeploymentTracker - The deployment status for a ring
type FleetControlRingsDeploymentTracker struct {
	// Rollout end time
	CompletedAt nrtime.EpochMilliseconds `json:"completedAt,omitempty"`
	// Ring name
	Name string `json:"name"`
	// Rollout start time
	StartedAt nrtime.EpochMilliseconds `json:"startedAt,omitempty"`
	// Ring deployment status
	Status string `json:"status"`
}

// FleetControlScopedReference - Scoped properties of an entity
type FleetControlScopedReference struct {
	// Scope id of the entity
	ID string `json:"id"`
	// Scope type of the entity
	Type FleetControlEntityScope `json:"type"`
}

// FleetControlScopedReferenceInput - Scoped reference input
type FleetControlScopedReferenceInput struct {
	// Scope id of the entity
	ID string `json:"id"`
	// Scope type of the entity
	Type FleetControlEntityScope `json:"type"`
}

// FleetControlTag - Collection of tags
type FleetControlTag struct {
	// The tag key
	Key string `json:"key"`
	// List of tag values
	Values []string `json:"values"`
}

// FleetControlTagInput - Collection of tags
type FleetControlTagInput struct {
	// The tag key
	Key string `json:"key"`
	// List of tag values
	Values []string `json:"values"`
}

// FleetControlUpdateFleetEntityInput - Fleet entity update input
type FleetControlUpdateFleetEntityInput struct {
	// Fleet entity description
	Description string `json:"description,omitempty"`
	// Fleet entity name
	Name string `json:"name,omitempty"`
	// Fleet entity tags
	Tags []FleetControlTagInput `json:"tags,omitempty"`
}

// FleetControlUpdateFleetResult - The result of updating a fleet
type FleetControlUpdateFleetResult struct {
	// The updated fleet entity
	Entity FleetControlFleetEntityResult `json:"entity"`
}
