// Code generated by tutone: DO NOT EDIT
package ai

// AiWorkflowsNRQLConfigurationDto - Enrichment configuration for NRQL type
type AiWorkflowsNRQLConfigurationDto struct {
	// The NRQL query
	Query string `json:"query"`
}

func (x *AiWorkflowsNRQLConfigurationDto) ImplementsAiWorkflowsConfigurationDto() {}

// AiNotificationsError - Notifications error interface
type AiNotificationsError struct {
}

func (x *AiNotificationsError) ImplementsAiNotificationsError() {}

// AiNotificationsErrorInterface - Notifications error interface
type AiNotificationsErrorInterface interface {
	ImplementsAiNotificationsError()
}
