// Code generated by tutone: DO NOT EDIT
package ai

// AiWorkflowsConfiguration - Workflows configuration interface
type AiWorkflowsConfiguration struct {
}

func (x *AiWorkflowsConfiguration) ImplementsAiWorkflowsConfiguration() {}

// AiWorkflowsConfigurationInterface - Enrichment configuration object
type AiWorkflowsConfigurationInterface interface {
	ImplementsAiWorkflowsConfiguration()
}

// AiNotificationsError - Notifications error interface
type AiNotificationsError struct {
}

func (x *AiNotificationsError) ImplementsAiNotificationsError() {}

// AiNotificationsErrorInterface - Notifications error interface
type AiNotificationsErrorInterface interface {
	ImplementsAiNotificationsError()
}
