// Code generated by tutone: DO NOT EDIT
package tagging

import (
	"github.com/newrelic/newrelic-client-go/v2/internal/http"
	"github.com/newrelic/newrelic-client-go/v2/pkg/config"
	"github.com/newrelic/newrelic-client-go/v2/pkg/logging"
)

// Tagging is used for interacting with New Relic Tagging.
type Tagging struct {
	client http.Client
	logger logging.Logger
}

// New returns a new client for interacting with New Relic Tagging.
func New(config config.Config) Tagging {
	client := http.NewClient(config)

	pkg := Tagging{
		client: client,
		logger: config.GetLogger(),
	}

	return pkg
}
