// Code generated by tutone: DO NOT EDIT
package nrqldroprules

// Create new drop rule(s).
func (a *NrqlDropRules) NRQLDropRulesCreate(
	accountID int,
	rules []NRQLDropRulesCreateDropRuleInput,
) (*NRQLDropRulesCreateDropRuleResult, error) {

	resp := NRQLDropRulesCreateQueryResponse{}
	vars := map[string]interface{}{
		"accountId": accountID,
		"rules":     rules,
	}

	if err := a.client.NerdGraphQuery(NRQLDropRulesCreateMutation, vars, &resp); err != nil {
		return nil, err
	}

	return &resp.NRQLDropRulesCreateDropRuleResult, nil
}

type NRQLDropRulesCreateQueryResponse struct {
	NRQLDropRulesCreateDropRuleResult NRQLDropRulesCreateDropRuleResult `json:"NRQLDropRulesCreate"`
}

const NRQLDropRulesCreateMutation = `mutation(
	$accountId: Int!,
	$rules: [NrqlDropRulesCreateDropRuleInput]!,
) { nrqlDropRulesCreate(
	accountId: $accountId,
	rules: $rules,
) {
	successes {
		accountId
		action
		createdAt
		createdBy
		description
		id
		nrql
	}
} }`

// Delete drop rule(s) by id.
func (a *NrqlDropRules) NRQLDropRulesDelete(
	accountID int,
	ruleIds []int,
) (*NRQLDropRulesDeleteDropRuleResult, error) {

	resp := NRQLDropRulesDeleteQueryResponse{}
	vars := map[string]interface{}{
		"accountId": accountID,
		"ruleIds":   ruleIds,
	}

	if err := a.client.NerdGraphQuery(NRQLDropRulesDeleteMutation, vars, &resp); err != nil {
		return nil, err
	}

	return &resp.NRQLDropRulesDeleteDropRuleResult, nil
}

type NRQLDropRulesDeleteQueryResponse struct {
	NRQLDropRulesDeleteDropRuleResult NRQLDropRulesDeleteDropRuleResult `json:"NRQLDropRulesDelete"`
}

const NRQLDropRulesDeleteMutation = `mutation(
	$accountId: Int!,
	$ruleIds: [ID]!,
) { nrqlDropRulesDelete(
	accountId: $accountId,
	ruleIds: $ruleIds,
) {
	successes {
		accountId
		action
		createdAt
		createdBy
		description
		id
		nrql
	}
} }`

// List the drop rules for the given account
func (a *NrqlDropRules) GetList(
	accountID int,
) (*NRQLDropRulesListDropRulesResult, error) {

	resp := listResponse{}
	vars := map[string]interface{}{
		"accountID": accountID,
	}

	if err := a.client.NerdGraphQuery(getListQuery, vars, &resp); err != nil {
		return nil, err
	}

	return &resp.Actor.Account.NRQLDropRules.List, nil
}

const getListQuery = `query(
	$accountID: Int!,
) { actor { account(id: $accountID) { nrqlDropRules { list {
	error {
		description
		reason
	}
	rules {
		accountId
		action
		createdAt
		createdBy
		description
		id
		nrql
	}
} } } } }`
