// Code generated by tutone: DO NOT EDIT
package maintenancewindow

import "context"

// Creates a new maintenance window.
func (a *Maintenancewindow) MaintenanceWindowCreate(
	maintenanceWindow MaintenanceWindowConfigCreateInput,
) (*MaintenanceWindowConfigDefinition, error) {
	return a.MaintenanceWindowCreateWithContext(context.Background(),
		maintenanceWindow,
	)
}

// Creates a new maintenance window.
func (a *Maintenancewindow) MaintenanceWindowCreateWithContext(
	ctx context.Context,
	maintenanceWindow MaintenanceWindowConfigCreateInput,
) (*MaintenanceWindowConfigDefinition, error) {

	resp := MaintenanceWindowCreateQueryResponse{}
	vars := map[string]interface{}{
		"maintenanceWindow": maintenanceWindow,
	}

	if err := a.client.NerdGraphQueryWithContext(ctx, MaintenanceWindowCreateMutation, vars, &resp); err != nil {
		return nil, err
	}

	return &resp.MaintenanceWindowConfigDefinition, nil
}

type MaintenanceWindowCreateQueryResponse struct {
	MaintenanceWindowConfigDefinition MaintenanceWindowConfigDefinition `json:"MaintenanceWindowCreate"`
}

const MaintenanceWindowCreateMutation = `mutation(
	$maintenanceWindow: MaintenanceWindowConfigCreateInput!,
) { maintenanceWindowCreate(
	maintenanceWindow: $maintenanceWindow,
) {
	affectedEntities
	affectedEntityType
	description
	duration
	id
	metadata {
		createdAt
		createdBy {
			id
		}
		updatedAt
		updatedBy {
			id
		}
	}
	name
	rrule
	scope {
		id
		type
	}
	startTime
	timezone
} }`

// Delete a maintenance window by the GUID.
func (a *Maintenancewindow) MaintenanceWindowDelete(
	iD int,
) (*MaintenanceWindowConfigDefinition, error) {
	return a.MaintenanceWindowDeleteWithContext(context.Background(),
		iD,
	)
}

// Delete a maintenance window by the GUID.
func (a *Maintenancewindow) MaintenanceWindowDeleteWithContext(
	ctx context.Context,
	iD int,
) (*MaintenanceWindowConfigDefinition, error) {

	resp := MaintenanceWindowDeleteQueryResponse{}
	vars := map[string]interface{}{
		"id": iD,
	}

	if err := a.client.NerdGraphQueryWithContext(ctx, MaintenanceWindowDeleteMutation, vars, &resp); err != nil {
		return nil, err
	}

	return &resp.MaintenanceWindowConfigDefinition, nil
}

type MaintenanceWindowDeleteQueryResponse struct {
	MaintenanceWindowConfigDefinition MaintenanceWindowConfigDefinition `json:"MaintenanceWindowDelete"`
}

const MaintenanceWindowDeleteMutation = `mutation(
	$id: ID!,
) { maintenanceWindowDelete(
	id: $id,
) {
	affectedEntities
	affectedEntityType
	description
	duration
	id
	metadata {
		createdAt
		updatedAt
	}
	name
	rrule
	scope {
		id
		type
	}
	startTime
	timezone
} }`

// Updates a maintenance window by the GUID.
func (a *Maintenancewindow) MaintenanceWindowUpdate(
	iD int,
	maintenanceWindow MaintenanceWindowConfigUpdateInput,
) (*MaintenanceWindowConfigDefinition, error) {
	return a.MaintenanceWindowUpdateWithContext(context.Background(),
		iD,
		maintenanceWindow,
	)
}

// Updates a maintenance window by the GUID.
func (a *Maintenancewindow) MaintenanceWindowUpdateWithContext(
	ctx context.Context,
	iD int,
	maintenanceWindow MaintenanceWindowConfigUpdateInput,
) (*MaintenanceWindowConfigDefinition, error) {

	resp := MaintenanceWindowUpdateQueryResponse{}
	vars := map[string]interface{}{
		"id":                iD,
		"maintenanceWindow": maintenanceWindow,
	}

	if err := a.client.NerdGraphQueryWithContext(ctx, MaintenanceWindowUpdateMutation, vars, &resp); err != nil {
		return nil, err
	}

	return &resp.MaintenanceWindowConfigDefinition, nil
}

type MaintenanceWindowUpdateQueryResponse struct {
	MaintenanceWindowConfigDefinition MaintenanceWindowConfigDefinition `json:"MaintenanceWindowUpdate"`
}

const MaintenanceWindowUpdateMutation = `mutation(
	$id: ID!,
	$maintenanceWindow: MaintenanceWindowConfigUpdateInput!,
) { maintenanceWindowUpdate(
	id: $id,
	maintenanceWindow: $maintenanceWindow,
) {
	affectedEntities
	affectedEntityType
	description
	duration
	id
	metadata {
		createdAt
		createdBy {
			id
		}
		updatedAt
		updatedBy {
			id
		}
	}
	name
	rrule
	scope {
		id
		type
	}
	startTime
	timezone
} }`

// Fetch maintenance window configurations by affected entity ID.
func (a *Maintenancewindow) GetListByAffectedEntityId(
	affectedEntityId int,
) (*MaintenanceWindowConfigResult, error) {
	return a.GetListByAffectedEntityIdWithContext(context.Background(),
		affectedEntityId,
	)
}

// Fetch maintenance window configurations by affected entity ID.
func (a *Maintenancewindow) GetListByAffectedEntityIdWithContext(
	ctx context.Context,
	affectedEntityId int,
) (*MaintenanceWindowConfigResult, error) {

	resp := listByAffectedEntityIdResponse{}
	vars := map[string]interface{}{
		"affectedEntityId": affectedEntityId,
	}

	if err := a.client.NerdGraphQueryWithContext(ctx, getListByAffectedEntityIdQuery, vars, &resp); err != nil {
		return nil, err
	}

	return &resp.Actor.MaintenanceWindow.ListByAffectedEntityId, nil
}

const getListByAffectedEntityIdQuery = `query(
	$affectedEntityId: ID!,
) { actor { maintenanceWindow { listByAffectedEntityId(
	affectedEntityId: $affectedEntityId,
) {
	maintenanceWindows {
		affectedEntities
		affectedEntityType
		description
		duration
		id
		name
		rrule
		startTime
		timezone
	}
} } } }`

// Fetch maintenance window configurations by their IDs.
func (a *Maintenancewindow) GetListByIds(
	iDs []int,
) (*MaintenanceWindowConfigResult, error) {
	return a.GetListByIdsWithContext(context.Background(),
		iDs,
	)
}

// Fetch maintenance window configurations by their IDs.
func (a *Maintenancewindow) GetListByIdsWithContext(
	ctx context.Context,
	iDs []int,
) (*MaintenanceWindowConfigResult, error) {

	resp := listByIdsResponse{}
	vars := map[string]interface{}{
		"ids": iDs,
	}

	if err := a.client.NerdGraphQueryWithContext(ctx, getListByIdsQuery, vars, &resp); err != nil {
		return nil, err
	}

	return &resp.Actor.MaintenanceWindow.ListByIds, nil
}

const getListByIdsQuery = `query(
	$ids: [ID!]!,
) { actor { maintenanceWindow { listByIds(
	ids: $ids,
) {
	maintenanceWindows {
		affectedEntities
		affectedEntityType
		description
		duration
		id
		metadata {
			createdAt
			createdBy {
				id
			}
			updatedAt
			updatedBy {
				id
			}
		}
		name
		rrule
		scope {
			id
			type
		}
		startTime
		timezone
	}
} } } }`
