// Code generated by tutone: DO NOT EDIT
package maintenancewindow

import (
	"github.com/newrelic/newrelic-client-go/v2/pkg/nrtime"
)

// MaintenanceWindowAffectedEntityType - Entity Type of the affected entities
type MaintenanceWindowAffectedEntityType string

var MaintenanceWindowAffectedEntityTypeTypes = struct {
	// Service Level
	SERVICE_LEVEL MaintenanceWindowAffectedEntityType
}{
	// Service Level
	SERVICE_LEVEL: "SERVICE_LEVEL",
}

// MaintenanceWindowEntityScope - The list of possible scopes of an entity
type MaintenanceWindowEntityScope string

var MaintenanceWindowEntityScopeTypes = struct {
	// Account scope
	ACCOUNT MaintenanceWindowEntityScope
	// Organization scope
	ORGANIZATION MaintenanceWindowEntityScope
}{
	// Account scope
	ACCOUNT: "ACCOUNT",
	// Organization scope
	ORGANIZATION: "ORGANIZATION",
}

// MaintenanceWindowActor - Represents an actor
type MaintenanceWindowActor struct {
	// Id of the actor
	ID int `json:"id"`
}

// MaintenanceWindowConfigCreateInput - The input object that represents the maintenance window that will be created.
type MaintenanceWindowConfigCreateInput struct {
	// The entities affected by the maintenance window.
	AffectedEntities []int `json:"affectedEntities,omitempty"`
	// The type of the entities affected by maintenance window.
	AffectedEntityType MaintenanceWindowAffectedEntityType `json:"affectedEntityType"`
	// The description of the maintenance window.
	Description string `json:"description,omitempty"`
	// The duration of the maintenance window.
	Duration Duration `json:"duration"`
	// The name of the maintenance window.
	Name string `json:"name"`
	// The Recurrence Rule of the maintenance window.
	Rrule string `json:"rrule,omitempty"`
	// The scope the maintenance window belongs to.
	Scope MaintenanceWindowScopedReferenceInput `json:"scope,omitempty"`
	// The start time of the maintenance window in ISO 8601 format.
	StartTime NaiveDateTime `json:"startTime"`
	// The timezone of the maintenance window.
	Timezone string `json:"timezone"`
}

// MaintenanceWindowConfigDefinition - The object that represents the Configuration of a Maintenance Window.
type MaintenanceWindowConfigDefinition struct {
	// The entities affected by the maintenance window.
	AffectedEntities []int `json:"affectedEntities,omitempty"`
	// The type of the entities affected by maintenance window.
	AffectedEntityType MaintenanceWindowAffectedEntityType `json:"affectedEntityType"`
	// The description of the maintenance window.
	Description string `json:"description,omitempty"`
	// The duration of the maintenance window.
	Duration Duration `json:"duration"`
	// The unique identifier for the maintenance window.
	ID int `json:"id"`
	// Metadata about the maintenance window.
	Metadata MaintenanceWindowMetadata `json:"metadata"`
	// The name of the maintenance window.
	Name string `json:"name"`
	// The Recurrence Rule of the maintenance window.
	Rrule string `json:"rrule,omitempty"`
	// The scope the maintenance window belongs to.
	Scope MaintenanceWindowScopedReference `json:"scope"`
	// The start time of the maintenance window in ISO 8601 format.
	StartTime NaiveDateTime `json:"startTime"`
	// The timezone of the maintenance window.
	Timezone string `json:"timezone"`
}

// MaintenanceWindowConfigResult - The response containing the list of maintenance windows matching the input filter.
type MaintenanceWindowConfigResult struct {
	// The list of maintenance windows matching the input filter.
	MaintenanceWindows []MaintenanceWindowConfigDefinition `json:"maintenanceWindows"`
}

// MaintenanceWindowConfigUpdateInput - The input object that represents the maintenance window that will be updated.
type MaintenanceWindowConfigUpdateInput struct {
	// The entities affected by the maintenance window.
	AffectedEntities []int `json:"affectedEntities,omitempty"`
	// The description of the maintenance window.
	Description string `json:"description,omitempty"`
	// The duration of the maintenance window.
	Duration Duration `json:"duration,omitempty"`
	// The name of the maintenance window.
	Name string `json:"name,omitempty"`
	// The Recurrence Rule of the maintenance window.
	Rrule string `json:"rrule,omitempty"`
	// The start time of the maintenance window in ISO 8601 format.
	StartTime NaiveDateTime `json:"startTime,omitempty"`
	// The timezone of the maintenance window.
	Timezone string `json:"timezone,omitempty"`
}

// MaintenanceWindowMetadata - Metadata of an entity
type MaintenanceWindowMetadata struct {
	// The entity's creation time
	CreatedAt nrtime.EpochMilliseconds `json:"createdAt,omitempty"`
	// Actor that created this entity
	CreatedBy MaintenanceWindowActor `json:"createdBy,omitempty"`
	// The entity's last update time
	UpdatedAt nrtime.EpochMilliseconds `json:"updatedAt,omitempty"`
	// Actor that updated this entity
	UpdatedBy MaintenanceWindowActor `json:"updatedBy,omitempty"`
}

// MaintenanceWindowScopedReference - Scoped properties of an entity
type MaintenanceWindowScopedReference struct {
	// Scope id of the entity
	ID int `json:"id"`
	// Scope type of the entity
	Type MaintenanceWindowEntityScope `json:"type"`
}

// MaintenanceWindowScopedReferenceInput - Scoped reference input
type MaintenanceWindowScopedReferenceInput struct {
	// Scope id of the entity
	ID int `json:"id"`
	// Scope type of the entity
	Type MaintenanceWindowEntityScope `json:"type"`
}

// Duration - The `Duration` scalar represents a period of time. A `Duration` appears as an ISO8601 formatted duration string.
type Duration string

// ID - The `ID` scalar type represents a unique identifier, often used to
// refetch an object or as key for a cache. The ID type appears in a JSON
// response as a String; however, it is not intended to be human-readable.
// When expected as an input type, any string (such as `"4"`) or integer
// (such as `4`) input value will be accepted as an ID.
type ID string

// NaiveDateTime - The `NaiveDateTime` scalar represents a date and time without a Time Zone. The `NaiveDateTime` appears as an ISO8601 formatted string.
type NaiveDateTime string
