// Code generated by tutone: DO NOT EDIT
package installevents

import (
	"github.com/newrelic/newrelic-client-go/pkg/nrtime"
)

type RecipeStatusType string

var RecipeStatusTypeTypes = struct {
	AVAILABLE   RecipeStatusType
	CANCELED    RecipeStatusType
	INSTALLED   RecipeStatusType
	INSTALLING  RecipeStatusType
	RECOMMENDED RecipeStatusType
	SKIPPED     RecipeStatusType
}{
	AVAILABLE:   "AVAILABLE",
	CANCELED:    "CANCELED",
	INSTALLED:   "INSTALLED",
	INSTALLING:  "INSTALLING",
	RECOMMENDED: "RECOMMENDED",
	SKIPPED:     "SKIPPED",
}

type InputInstallMetadata struct {
	CliVersion      string           `json:"cliVersion"`
	Complete        bool             `json:"complete"`
	Error           InputStatusError `json:"error,omitempty"`
	HostName        string           `json:"hostName"`
	KernelArch      string           `json:"kernelArch"`
	KernelVersion   string           `json:"kernelVersion"`
	LogFilePath     string           `json:"logFilePath"`
	Os              string           `json:"os"`
	Platform        string           `json:"platform"`
	PlatformFamily  string           `json:"platformFamily"`
	PlatformVersion string           `json:"platformVersion"`
	RedirectURL     string           `json:"redirectUrl,omitempty"`
	TargetedInstall bool             `json:"targetedInstall"`
}

type InputStatusError struct {
	Details string `json:"details,omitempty"`
	Message string `json:"message,omitempty"`
}

type InstallEvent struct {
	DisplayName                    string           `json:"displayName"`
	EntityGUID                     string           `json:"entityGuid"`
	Error                          StatusError      `json:"error"`
	Name                           string           `json:"name"`
	Status                         RecipeStatusType `json:"status"`
	Timestamp                      nrtime.DateTime  `json:"timestamp,omitempty"`
	ValidationDurationMilliseconds float64          `json:"validationDurationMilliseconds"`
}

type InstallMetadata struct {
	CliVersion      string      `json:"cliVersion"`
	Complete        bool        `json:"complete"`
	Error           StatusError `json:"error"`
	HostName        string      `json:"hostName"`
	KernelArch      string      `json:"kernelArch"`
	KernelVersion   string      `json:"kernelVersion"`
	LogFilePath     string      `json:"logFilePath"`
	Os              string      `json:"os"`
	Platform        string      `json:"platform"`
	PlatformFamily  string      `json:"platformFamily"`
	PlatformVersion string      `json:"platformVersion"`
	RedirectURL     string      `json:"redirectUrl,omitempty"`
	TargetedInstall bool        `json:"targetedInstall"`
}

type InstallStatus struct {
	DisplayName                    string           `json:"displayName"`
	EntityGUID                     string           `json:"entityGuid"`
	Error                          InputStatusError `json:"error,omitempty"`
	Name                           string           `json:"name"`
	Status                         RecipeStatusType `json:"status"`
	ValidationDurationMilliseconds float64          `json:"validationDurationMilliseconds"`
}

type StatusError struct {
	Details string `json:"details,omitempty"`
	Message string `json:"message,omitempty"`
}

// Float - The `Float` scalar type represents signed double-precision fractional values as specified by [IEEE 754](http://en.wikipedia.org/wiki/IEEE_floating_point).
type Float string
