// Code generated by tutone: DO NOT EDIT
package syntheticsv2

import "context"

// Create a Synthetic Script Api monitor
func (a *SyntheticsV2) SyntheticsCreateScriptAPIMonitor(
	accountID int,
	monitor SyntheticsCreateScriptAPIMonitorInput,
) (*SyntheticsScriptAPIMonitorCreateMutationResult, error) {
	return a.SyntheticsCreateScriptAPIMonitorWithContext(context.Background(),
		accountID,
		monitor,
	)
}

// Create a Synthetic Script Api monitor
func (a *SyntheticsV2) SyntheticsCreateScriptAPIMonitorWithContext(
	ctx context.Context,
	accountID int,
	monitor SyntheticsCreateScriptAPIMonitorInput,
) (*SyntheticsScriptAPIMonitorCreateMutationResult, error) {

	resp := SyntheticsCreateScriptAPIMonitorQueryResponse{}
	vars := map[string]interface{}{
		"accountId": accountID,
		"monitor":   monitor,
	}

	if err := a.client.NerdGraphQueryWithContext(ctx, SyntheticsCreateScriptAPIMonitorMutation, vars, &resp); err != nil {
		return nil, err
	}

	return &resp.SyntheticsScriptAPIMonitorCreateMutationResult, nil
}

type SyntheticsCreateScriptAPIMonitorQueryResponse struct {
	SyntheticsScriptAPIMonitorCreateMutationResult SyntheticsScriptAPIMonitorCreateMutationResult `json:"SyntheticsCreateScriptAPIMonitor"`
}

const SyntheticsCreateScriptAPIMonitorMutation = `mutation(
	$accountId: Int!,
	$monitor: SyntheticsCreateScriptApiMonitorInput!,
) { syntheticsCreateScriptApiMonitor(
	accountId: $accountId,
	monitor: $monitor,
) {
	errors {
		description
		type
	}
	monitor {
		createdAt
		guid
		modifiedAt
		name
		period
		status
	}
} }`
