name: Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.x

      - name: Add GOBIN to PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        shell: bash

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache deps
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Lint
        run: make lint

  test-unit:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.x

      - name: Add GOBIN to PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        shell: bash

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache deps
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Unit Tests
        run: make test-unit coverage-report-unit

      - name: Report unit test coverage via Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/unit.out
          flags: unit

      # - name: New Relic JUnit Reporter
      #   if: github.event.pull_request.head.repo.full_name == github.repository
      #   uses: newrelic/junit-reporter-action@v0.1.1
      #   with:
      #     accountId: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
      #     insertApiKey: ${{ secrets.NEW_RELIC_INSIGHTS_INSERT_KEY }}
      #     testOutputPath: coverage/unit.xml

  test-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.x

      - name: Add GOBIN to PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        shell: bash

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache deps
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Integration Tests
        if: github.event.pull_request.head.repo.full_name == github.repository
        run: make test-integration coverage-report-integration
        env:
          NEW_RELIC_ACCOUNT_ID: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
          NEW_RELIC_ADMIN_API_KEY: ${{ secrets.NEW_RELIC_ADMIN_API_KEY }}
          NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
          NEW_RELIC_INSIGHTS_INSERT_KEY: ${{ secrets.NEW_RELIC_INSIGHTS_INSERT_KEY }}
          NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
          NEW_RELIC_REGION: ${{ secrets.NEW_RELIC_REGION }}
          INTEGRATION_TESTING_AWS_ARN: ${{ secrets.INTEGRATION_TESTING_AWS_ARN }}
          INTEGRATION_TESTING_NEW_RELIC_ORGANIZATION_ID: ${{ secrets.INTEGRATION_TESTING_NEW_RELIC_ORGANIZATION_ID}}
          INTEGRATION_TESTING_NEW_RELIC_AUTHENTICATION_DOMAIN_ID: ${{ secrets.INTEGRATION_TESTING_NEW_RELIC_AUTHENTICATION_DOMAIN_ID}}

      - name: Report integration test coverage via Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/integration.out
          flags: integration

      # - name: New Relic JUnit Reporter
      #   if: github.event.pull_request.head.repo.full_name == github.repository
      #   uses: newrelic/junit-reporter-action@v0.1.1
      #   with:
      #     accountId: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
      #     insertApiKey: ${{ secrets.NEW_RELIC_INSIGHTS_INSERT_KEY }}
      #     testOutputPath: coverage/integration.xml
